class UserError(BaseException):
    pass

class CollectError(BaseException):
    pass